// Mocks generated by Mockito 5.4.6 from annotations
// in jobpet/test/repositories/user_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:jobpet/data/datasources/local/user_local_datasource.dart'
    as _i2;
import 'package:jobpet/data/models/user_profile.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDatasourceGenerated extends _i1.Mock
    implements _i2.UserLocalDatasource {
  @override
  _i3.Future<_i4.UserProfile?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i3.Future<_i4.UserProfile?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.UserProfile?>.value(),
          )
          as _i3.Future<_i4.UserProfile?>);

  @override
  _i3.Future<void> saveUser(_i4.UserProfile? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUser(_i4.UserProfile? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.UserProfile>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i3.Future<List<_i4.UserProfile>>.value(
              <_i4.UserProfile>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.UserProfile>>.value(
              <_i4.UserProfile>[],
            ),
          )
          as _i3.Future<List<_i4.UserProfile>>);
}
