// Mocks generated by Mockito 5.4.6 from annotations
// in jobpet/test/services/chat_service_rag_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jobpet/features/pet/data/models/retrieval_result.dart' as _i2;
import 'package:jobpet/features/pet/data/models/vector_memory.dart' as _i5;
import 'package:jobpet/features/pet/services/retrieval_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRetrievalResult_0 extends _i1.SmartFake
    implements _i2.RetrievalResult {
  _FakeRetrievalResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RetrievalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetrievalService extends _i1.Mock implements _i3.RetrievalService {
  MockRetrievalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RetrievalResult> search({
    required String? query,
    required String? petId,
    int? topK = 5,
    double? threshold = 0.0,
    _i5.MemoryType? filterType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #query: query,
              #petId: petId,
              #topK: topK,
              #threshold: threshold,
              #filterType: filterType,
            }),
            returnValue: _i4.Future<_i2.RetrievalResult>.value(
              _FakeRetrievalResult_0(
                this,
                Invocation.method(#search, [], {
                  #query: query,
                  #petId: petId,
                  #topK: topK,
                  #threshold: threshold,
                  #filterType: filterType,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.RetrievalResult>);

  @override
  _i4.Future<_i2.RetrievalResult> searchByTimeRange({
    required String? petId,
    required DateTime? start,
    required DateTime? end,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchByTimeRange, [], {
              #petId: petId,
              #start: start,
              #end: end,
              #limit: limit,
            }),
            returnValue: _i4.Future<_i2.RetrievalResult>.value(
              _FakeRetrievalResult_0(
                this,
                Invocation.method(#searchByTimeRange, [], {
                  #petId: petId,
                  #start: start,
                  #end: end,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.RetrievalResult>);

  @override
  _i4.Future<void> addMemory({
    required String? petId,
    required String? content,
    required _i5.MemoryType? type,
    required _i5.MemoryCategory? category,
    double? importance = 0.5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMemory, [], {
              #petId: petId,
              #content: content,
              #type: type,
              #category: category,
              #importance: importance,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
