// Mocks generated by Mockito 5.4.6 from annotations
// in jobpet/test/services/embedding_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:jobpet/features/pet/services/embedding_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [EmbeddingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmbeddingService extends _i1.Mock implements _i2.EmbeddingService {
  MockEmbeddingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get dimension =>
      (super.noSuchMethod(Invocation.getter(#dimension), returnValue: 0)
          as int);

  @override
  String get providerName =>
      (super.noSuchMethod(
            Invocation.getter(#providerName),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#providerName),
            ),
          )
          as String);

  @override
  _i4.Future<List<double>> embed(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#embed, [text]),
            returnValue: _i4.Future<List<double>>.value(<double>[]),
          )
          as _i4.Future<List<double>>);

  @override
  _i4.Future<List<List<double>>> embedBatch(List<String>? texts) =>
      (super.noSuchMethod(
            Invocation.method(#embedBatch, [texts]),
            returnValue: _i4.Future<List<List<double>>>.value(<List<double>>[]),
          )
          as _i4.Future<List<List<double>>>);

  @override
  _i4.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
